Address Sequence contains more than one element exception and some clean-ups.
frankhommers/Hangfire.PostgreSql pull request #177
Opened 2020-11-23 17:57 UTC by rezabayesteh

2020-11-24 14:00 UTC, yongliu-mdsol approved these changes
LGTM

2020-11-24 19:07 UTC, vytautask requested changes

2020-11-24 19:07 UTC, vytautask commented on tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Let's not upgrade to 5.0 yet.

2020-11-25 00:41 UTC, rezabayesteh commented on tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Done

2020-11-25 07:37 UTC, merged