Implemented Counters Aggregator
frankhommers/Hangfire.PostgreSql pull request #268
Opened 2022-10-19 19:23 UTC by jgennari

Using Hangfire.SqlServer as a reference I implemented the counters aggregator functionality. The actual SQL implementation differs a bit (due to `MERGE` only being available in PostgreSQL 15 but I'm basically doing an upsert in the aggregate table, then deleting the records from the counters table, all within a transaction.

I also updated `PostgreSqlMonitoringApi.cs` to pull in the two values via a `UNION ALL` and sum them together, exactly as seen in the SQL Server implementation. Finally, I updated `ExpirationManager.cs` to expire old records in the new aggregate table. 

I'm unfamiliar with the schema management system here, so I just created a new v18 install script. If someone could test that functionality, that would be great.

2022-10-19 20:20 UTC, frankhommers requested changes

2022-10-19 20:20 UTC, frankhommers commented on src/Hangfire.PostgreSql/Scripts/Install.v18.sql
> +create table aggregatedcounter (
Our SQL style is mostly uppercased

2022-10-19 20:20 UTC, frankhommers commented on src/Hangfire.PostgreSql/CountersAggregator.cs
> +insert into ""{_storage.Options.SchemaName}"".""aggregatedcounter"" (""key"", ""value"", ""expireat"")
Our SQL style is mostly uppercased

2022-10-19 20:20 UTC, frankhommers commented on src/Hangfire.PostgreSql/PostgreSqlConnection.cs
> +      string query = $@"SELECT SUM(""VALUE"") FROM (
Please change to `$@"SELECT SUM(""value"") FROM`

2022-10-19 20:20 UTC, frankhommers commented on src/Hangfire.PostgreSql/PostgreSqlConnection.cs
> +            SELECT SUM(""value"") VALUE FROM ""{_options.SchemaName}"".""counter"" WHERE ""key"" = @Key
Please change to `SELECT SUM(""value"") ""value"" FROM ""{_options.SchemaName}"".""counter"" WHERE ""key"" = @Key`

2022-10-19 20:20 UTC, frankhommers commented on src/Hangfire.PostgreSql/PostgreSqlConnection.cs
> +            SELECT SUM(""value"") VALUE FROM ""{_options.SchemaName}"".""aggregatedcounter"" WHERE ""key"" = @Key) c";
Please change to `SELECT SUM(""value"") ""value"" FROM ""{_options.SchemaName}"".""aggregatedcounter"" WHERE ""key"" = @Key) c";`

2022-10-19 20:21 UTC, frankhommers commented
Nice work, only out of style with us a bit ;-)

2022-10-19 21:38 UTC, jgennari commented
I think I got all of them cleaned up, let me know if I missed any.

2022-10-20 06:12 UTC, azygis requested changes

2022-10-20 15:23 UTC, jgennari commented on src/Hangfire.PostgreSql/CountersAggregator.cs
> +    public override string ToString()
Definitely.

2022-10-20 17:09 UTC, azygis approved these changes

2022-10-24 17:43 UTC, jgennari commented
@frankhommers let me know if there's anything else you see here.

2022-10-24 17:46 UTC, frankhommers approved these changes

2022-10-24 17:46 UTC, merged

2022-10-25 11:18 UTC, frankhommers commented
@jgennari Something went wrong with schema-versions. Now some tests fail: 

https://ci.appveyor.com/project/vytautask/hangfire-postgresql-lel5h/branch/master/job/utmr8tbildrm7kqd/tests

2022-10-25 11:33 UTC, jgennari commented
Sure! I'll take a look shortly.