Codespaces/Long polling
frankhommers/Hangfire.PostgreSql pull request #289
Opened 2023-02-27 07:06 UTC by b-rain-m

Support for Codespaces
- Added .devcontainer folder.
- Develop straight from Github by going to Code -> Codespaces.
- Containers include PostgreSQL 12 and VS Code extension to connect to database.
- Containers also include extension for tests allowing easy access to test cases.

Support for Long polling
- Added `EnableLongPolling` option which when enabled for PostgreSQL 11+ will use notifications to interrupt polling interrupts.
- This allows for very long polling times (e.g. 10 minutes) that end immediately when jobs are queued.
- Because this feature uses Postgres notifications it should work across multiple processes across multiple machines as long as they share the same database.

2023-03-03 07:49 UTC, azygis commented
I will not pretend I know what the codespaces is as I always work inside IDEs so my review is strictly for the implementation of polling. It's probably safe to assume it's all correctly configured!

2023-03-03 14:45 UTC, frankhommers commented
@azygis What is your review conclusion? :P

2023-03-03 14:46 UTC, azygis requested changes

2023-03-03 14:46 UTC, azygis commented
☝️ 

Changes needed.

2023-03-04 05:19 UTC, azygis approved these changes

2023-03-04 05:20 UTC, merged

2023-03-04 05:20 UTC, azygis commented
Thank you!